In [3]:
import csv as csv
import numpy as np

csv_file_object = csv.reader(open('train.csv', 'rb')) 
header = csv_file_object.next() 
data=[] 

for row in csv_file_object:
    data.append(row)
data = np.array(data) 

In [4]:
np.ndarray

numpy.ndarray

In [5]:
import pandas as pd
import numpy as np

# For .read_csv, always use header=0 when you know row 0 is the header row
df = pd.read_csv('train.csv', header=0)


In [6]:
df[df['Age'].isnull()][['Sex', 'Pclass', 'Age']].head()

Sex  Pclass  Age
5     male       3  NaN
17    male       2  NaN
19  female       3  NaN
26    male       3  NaN
28  female       3  NaN

In [7]:
for i in range(1,4):
    print i, len(df[ (df['Sex'] == 'male') & (df['Pclass'] == i) ])

1 122
2 108
3 347


In [8]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [9]:
df['Gender'] = 4

In [10]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  Gender  
0      0         A/5 21171   7.2500   NaN        S       4  
1      0          PC 17599  71.2833   C85        C       4  
2      0  STON/O2. 3101282   7.9250   NaN        S       4  
3      0            113803  53.1000  C123        S       4  
4      0            373450   8.0500   NaN        S       4

In [11]:
df['Gender'] = df['Sex'].map( lambda x: x[0].upper() )

In [12]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked Gender  
0      0         A/5 21171   7.2500   NaN        S      M  
1      0          PC 17599  71.2833   C85        C      F  
2      0  STON/O2. 3101282   7.9250   NaN        S      F  
3      0            113803  53.1000  C123        S      F  
4      0            373450   8.0500   NaN        S      M

In [13]:
df['Gender'] = df['Sex'].map( {'female': 0, 'male': 1} ).astype(int)

In [14]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  Gender  
0      0         A/5 21171   7.2500   NaN        S       1  
1      0          PC 17599  71.2833   C85        C       0  
2      0  STON/O2. 3101282   7.9250   NaN        S       0  
3      0            113803  53.1000  C123        S       0  
4      0            373450   8.0500   NaN        S       1

In [15]:
median_ages = np.zeros((2,3))
median_ages

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
for i in range(0, 2):
    for j in range(0, 3):
        median_ages[i,j] = df[(df['Gender'] == i) & (df['Pclass'] == j+1)]['Age'].dropna().median()
 
median_ages

array([[ 35. ,  28. ,  21.5],
       [ 40. ,  30. ,  25. ]])

In [17]:
df[(df['Gender'] == 0) & (df['Pclass'] == 2)]['Age'].median()

28.0

In [18]:
df['AgeFill'] = df['Age']
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  Gender  AgeFill  
0      0         A/5 21171   7.2500   NaN        S       1       22  
1      0          PC 17599  71.2833   C85        C       0       38  
2      0  STON/O2. 3101282   7.9250   NaN        S       0       26  
3      0            113803  53.1000  C123        S       0       35  
4      0            373450   8.0500   NaN        S       1       35

In [19]:
df[ df['Age'].isnull() ][['Gender','Pclass','Age','AgeFill']].head(10)

Gender  Pclass  Age  AgeFill
5        1       3  NaN      NaN
17       1       2  NaN      NaN
19       0       3  NaN      NaN
26       1       3  NaN      NaN
28       0       3  NaN      NaN
29       1       3  NaN      NaN
31       0       1  NaN      NaN
32       0       3  NaN      NaN
36       1       3  NaN      NaN
42       1       3  NaN      NaN

In [20]:
for i in range(0, 2):
    for j in range(0, 3):
        df.loc[ (df.Age.isnull()) & (df.Gender == i) & (df.Pclass == j+1), 'AgeFill'] \
        = median_ages[i,j]

df[ df['Age'].isnull() ][['Gender','Pclass','Age','AgeFill']].head(10)

Gender  Pclass  Age  AgeFill
5        1       3  NaN     25.0
17       1       2  NaN     30.0
19       0       3  NaN     21.5
26       1       3  NaN     25.0
28       0       3  NaN     21.5
29       1       3  NaN     25.0
31       0       1  NaN     35.0
32       0       3  NaN     21.5
36       1       3  NaN     25.0
42       1       3  NaN     25.0

In [21]:
df['AgeisNull'] = pd.isnull(df.AgeFill).astype(int)
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare      Gender     AgeFill  AgeisNull  
count  891.000000  891.000000  891.000000  891.000000        891  
mean     0.381594   32.204208    0.647587   29.112424          0  
std      0.806057   49.693429    0.477990   13.304424          0  
min      0.000000    0.000000    0.000000    0.420000          0  
25%      0.000000    7.910400    0.000000   21.500000          0  
50%      0.000000   14.454200    1.000000   26.000000          0  
75%      0.000000   31.000000    1.000000   36.000000          0  
max      6.000000  512.329200    1.000000   80.000000          0

In [22]:
df['FamilySize'] = df['SibSp'] = df['Parch']

In [23]:
df['Age*Pclass'] = df.AgeFill * df.Pclass

In [24]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      0   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      0   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  Gender  AgeFill  \
0      0         A/5 21171   7.2500   NaN        S       1       22   
1      0          PC 17599  71.2833   C85        C       0       38   
2      0  STON/O2. 3101282   7.9250   NaN        S       0       26   
3      0            113803  53.1000  C123        S       0       35   
4      0            373450   8.0500   NaN        S       1       35   

   AgeisNull  FamilySize  Age*Pclass  
0          0           0          66  
1          0           0          38  
2          0           0          78  
3          0           0          35  
4          0           0         105

In [25]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
Gender           int64
AgeFill        float64
AgeisNull        int64
FamilySize       int64
Age*Pclass     float64
dtype: object

In [26]:
df.dtypes[df.dtypes.map(lambda x : x == 'object')]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [27]:
tempo = df.drop(['Name','Sex','Ticket','Age','Cabin','Embarked','PassengerId'], axis = 1)

In [28]:
tempo.head()

Survived  Pclass  SibSp  Parch     Fare  Gender  AgeFill  AgeisNull  \
0         0       3      0      0   7.2500       1       22          0   
1         1       1      0      0  71.2833       0       38          0   
2         1       3      0      0   7.9250       0       26          0   
3         1       1      0      0  53.1000       0       35          0   
4         0       3      0      0   8.0500       1       35          0   

   FamilySize  Age*Pclass  
0           0          66  
1           0          38  
2           0          78  
3           0          35  
4           0         105

In [29]:
train_data = tempo.values

In [38]:
train_data[0::,1::]

array([[  3. ,   0. ,   0. , ...,   0. ,   0. ,  66. ],
       [  1. ,   0. ,   0. , ...,   0. ,   0. ,  38. ],
       [  3. ,   0. ,   0. , ...,   0. ,   0. ,  78. ],
       ..., 
       [  3. ,   2. ,   2. , ...,   0. ,   2. ,  64.5],
       [  1. ,   0. ,   0. , ...,   0. ,   0. ,  26. ],
       [  3. ,   0. ,   0. , ...,   0. ,   0. ,  96. ]])

In [44]:
train_data[3::,0::]

array([[   1. ,    1. ,    0. , ...,    0. ,    0. ,   35. ],
       [   0. ,    3. ,    0. , ...,    0. ,    0. ,  105. ],
       [   0. ,    3. ,    0. , ...,    0. ,    0. ,   75. ],
       ..., 
       [   0. ,    3. ,    2. , ...,    0. ,    2. ,   64.5],
       [   1. ,    1. ,    0. , ...,    0. ,    0. ,   26. ],
       [   0. ,    3. ,    0. , ...,    0. ,    0. ,   96. ]])

In [39]:
train_data[0::,0]

array([ 0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,
        0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,
        0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [31]:
train_data[0:5]

array([[   0.    ,    3.    ,    0.    ,    0.    ,    7.25  ,    1.    ,
          22.    ,    0.    ,    0.    ,   66.    ],
       [   1.    ,    1.    ,    0.    ,    0.    ,   71.2833,    0.    ,
          38.    ,    0.    ,    0.    ,   38.    ],
       [   1.    ,    3.    ,    0.    ,    0.    ,    7.925 ,    0.    ,
          26.    ,    0.    ,    0.    ,   78.    ],
       [   1.    ,    1.    ,    0.    ,    0.    ,   53.1   ,    0.    ,
          35.    ,    0.    ,    0.    ,   35.    ],
       [   0.    ,    3.    ,    0.    ,    0.    ,    8.05  ,    1.    ,
          35.    ,    0.    ,    0.    ,  105.    ]])

In [32]:
import csv as csv
import numpy as np

csv_file_object = csv.reader(open('test.csv', 'rb')) 
header = csv_file_object.next() 
datas=[] 

for row in csv_file_object:
    datas.append(row)
datas = np.array(data) 
np.ndarray

numpy.ndarray

In [33]:
thetest = np.delete(datas,0,1)

In [34]:
thetest[1:5]

array([['1', '1', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
        'female', '38', '1', '0', 'PC 17599', '71.2833', 'C85', 'C'],
       ['1', '3', 'Heikkinen, Miss. Laina', 'female', '26', '0', '0',
        'STON/O2. 3101282', '7.925', '', 'S'],
       ['1', '1', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female',
        '35', '1', '0', '113803', '53.1', 'C123', 'S'],
       ['0', '3', 'Allen, Mr. William Henry', 'male', '35', '0', '0',
        '373450', '8.05', '', 'S']], 
      dtype='|S82')

In [35]:

import csv as csv
import numpy as np

csv_file_object = csv.reader(open('test.csv', 'rb')) 
header = csv_file_object.next() 
test_data=[] 

for row in csv_file_object:
    test_data.append(row)
    
test_data = np.array(data)


# Import the random forest package
from sklearn.ensemble import RandomForestClassifier 

# Create the random forest object which will include all the parameters
# for the fit
forest = RandomForestClassifier(n_estimators = 100)

# Fit the training data to the Survived labels and create the decision trees
forest = forest.fit(train_data[0::,1::],train_data[0::,0])

# Take the same decision trees and run it on the test data
output = forest.predict(test_data)

ValueError: could not convert string to float: Braund, Mr. Owen Harris